config/routes.rb
Rails.application.routes.draw do
  
  # devise_for :admins, controllers: {
  #   sessions:      'admins/sessions'
  # }
  devise_for :end_users, controllers: {
    sessions:      'end_users/sessions',
    passwords:     'end_users/passwords',
    registrations: 'end_users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'about' => 'homes#about', as: 'about'
  
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    get 'favorites' => 'teammate_favorites#index'
    # resources :teammate_favorites, only: [:index]
    resources :group_users, only: [:index]
  end
  resources :groups, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get 'post_index' => 'groups#post_index'
    get 'menber_index' => 'groups#menber_index'
    resources :matchmakes, only: [:new, :create, :edit, :update, :destroy] 
    resources :teammate_recruitments, only: [:new, :create, :edit, :update, :destroy] 
    resource :group_users, only: [:create, :destroy]
  end
  resources :teammate_recruitments, only: [:index, :show] do
    resources :teammate_comments, only: [:create, :destroy]
    resource :teammate_favorites, only: [:create, :destroy]
  end
  resources :matchmakes, only: [:index, :show] do
    resources :matchmake_comments, only: [:create, :destroy]
    resource :matchmake_favorites, only: [:create, :destroy]
  end
  

end

app/models/matchmake_favorite.rb
class MatchmakeFavorite < ApplicationRecord
  belongs_to :matchmake
  belongs_to :end_user
end

app/controllers/matchmake_favorites_controller.rb
class MatchmakeFavoritesController < ApplicationController
  before_action :authenticate_end_user!
  def create
    @matchmake =Matchmake.find(params[:matchmake_id])
    favorite = current_end_user.matchmake_favorites.new(matchmake_id: @matchmake.id)
    favorite.save
  end
  def destroy
    @matchmake =Matchmake.find(params[:matchmake_id])
    favorite = current_end_user.matchmake_favorites.find_by(matchmake_id: @matchmake.id)
    favorite.destroy
  end
end

app/helpers/matchmake_favorites_helper.rb
module MatchmakeFavoritesHelper
end

app/views/matchmake_favorites/_favorites_button.html.erb
 <% if end_user_signed_in?%>
  <% if matchmake.favorited_by?(current_end_user) %>
      <%= link_to  matchmake_matchmake_favorites_path(@matchmake), method: :delete, remote: true do %>
        <i class="far fa-futbol" aria-hidden="true" style="color: red;"></i>
        <%= "お気に入りを削除" %>
      <% end %>
  <% else %>
      <%= link_to matchmake_matchmake_favorites_path(@matchmake), method: :post, remote: true do %>
        <i class="far fa-futbol" aria-hidden="true"></i>
        <%= "お気に入りに追加" %> 
      <% end %>
  <% end %>
<% end %>

app/views/matchmake_favorites/_matchmake_favorite.html.erb
<div class="row">
  <div class="col-10 offset-1">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>投稿タイトル</th>
          <th>募集カテゴリー</th>
          <th>募集レベル</th>
          <th>投稿日</th>
          <th></th>
        </tr>
      </thead>
      <% @matchmake_favorites.each do |favorite| %>
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag favorite.matchmake.group, :group_image, :fill, 50, 50,format: 'jpeg', fallback: "no_image.jpg", size: "50x50"%>
            </td>
            <td>
              <%= favorite.matchmake.title %>
            </td>
            <td>
              <%= favorite.matchmake.category %>
            </td>
            <td>
              <%= favorite.matchmake.level %>
            </td>
            <td>
              <%= favorite.matchmake.created_at.strftime("%Y年%m月%d日") %>
            </td>
            <td>
              <%= link_to "詳細へ", matchmake_path(favorite.matchmake_id),class: "nav-link" %>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
    <%= paginate @matchmake_favorites, class: "paginate" %>
  </div>
</div>

app/views/matchmake_favorites/create.js.erb
$('#favorites_buttons_<%= @matchmake.id %>').html("<%= j(render partial: 'matchmake_favorites/favorites_button', locals: {matchmake: @matchmake}) %>");

app/views/matchmake_favorites/destroy.js.erb
$('#favorites_buttons_<%= @matchmake.id %>').html("<%= j(render partial: 'matchmake_favorites/favorites_button', locals: {matchmake: @matchmake}) %>");

app/views/matchmake_favorites/index.html.erb
<h2>マッチメイク お気に入り一覧</h2>
<div class="row">
  <div class="col-10 offset-1">
    <table class="table">
      <thead>
        <tr>
          <th>投稿タイトル</th>
          <th>投稿日</th>
          <th></th>
        </tr>
      </thead>
      <% @favorites.each do |favorite| %>
        <tbody>
          <tr>
            <td>
              <%= favorite.matchmake.title %>
            </td>
            <td><%= favorite.matchmake.created_at.strftime("%Y年%m月%d日") %></td>
            <td>
              <%= link_to "詳細へ", matchmake_path(favorite.matchmake_id) %>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>