config/routes.rb
Rails.application.routes.draw do
  
  # devise_for :admins, controllers: {
  #   sessions:      'admins/sessions'
  # }
  devise_for :end_users, controllers: {
    sessions:      'end_users/sessions',
    passwords:     'end_users/passwords',
    registrations: 'end_users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'about' => 'homes#about', as: 'about'
  
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    get 'favorites' => 'teammate_favorites#index'
    # resources :teammate_favorites, only: [:index]
    resources :group_users, only: [:index]
  end
  resources :groups, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get 'post_index' => 'groups#post_index'
    get 'menber_index' => 'groups#menber_index'
    resources :matchmakes, only: [:new, :create, :edit, :update, :destroy] 
    resources :teammate_recruitments, only: [:new, :create, :edit, :update, :destroy] 
    resource :group_users, only: [:create, :destroy]
  end
  resources :teammate_recruitments, only: [:index, :show] do
    resources :teammate_comments, only: [:create, :destroy]
    resource :teammate_favorites, only: [:create, :destroy]
  end
  resources :matchmakes, only: [:index, :show] do
    resources :matchmake_comments, only: [:create, :destroy]
    resource :matchmake_favorites, only: [:create, :destroy]
  end
  

end

app/models/teammate_favorite.rb
class TeammateFavorite < ApplicationRecord
  belongs_to :teammate_recruitment
  belongs_to :end_user
end

app/controllers/teammate_favorites_controller.rb
class TeammateFavoritesController < ApplicationController
  before_action :authenticate_end_user!
  def index
    # メンバー募集のお気に入り一覧
    @teammate_favorites = TeammateFavorite.where(end_user_id: current_end_user.id).order(created_at: :desc).page(params[:page]).per(8)
    # マッチメイクのお気に入り一覧
    @matchmake_favorites = MatchmakeFavorite.where(end_user_id: current_end_user.id).order(created_at: :desc).page(params[:page]).per(8)
  end
  def create
    @teammate_recruitment =TeammateRecruitment.find(params[:teammate_recruitment_id])
    favorite = current_end_user.teammate_favorites.build(teammate_recruitment_id: @teammate_recruitment.id)
    favorite.save
  end
  def destroy
    @teammate_recruitment =TeammateRecruitment.find(params[:teammate_recruitment_id])
    favorite = current_end_user.teammate_favorites.find_by(teammate_recruitment_id: @teammate_recruitment.id)
    favorite.destroy
  end
end

app/helpers/teammate_favorites_helper.rb
module TeammateFavoritesHelper
end

app/views/teammate_favorites/_favorites_button.html.erb
<% if end_user_signed_in?%>
  <% if teammate_recruitment.favorited_by?(current_end_user) %>
      <%= link_to  teammate_recruitment_teammate_favorites_path(teammate_recruitment), method: :delete, remote: true do %>
        <i class="far fa-futbol" aria-hidden="true" style="color: red;"></i>
        <%= "お気に入りを削除" %>
      <% end %>
  <% else %>
      <%= link_to teammate_recruitment_teammate_favorites_path(teammate_recruitment), method: :post, remote: true do %>
        <i class="far fa-futbol" aria-hidden="true"></i>
        <%= "お気に入りに追加" %> 
      <% end %>
  <% end %>
<% end %>

app/views/teammate_favorites/_teammate_favorite.html.erb
<div class="row">
  <div class="col-10 offset-1">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>投稿タイトル</th>
          <th>カテゴリー</th>
          <th>チームレベル</th>
          <th>投稿日</th>
          <th></th>
        </tr>
      </thead>
      <% teammate_favorites.each do |favorite| %>
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag favorite.teammate_recruitment.group, :group_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size: "50x50"%>
            </td>
            <td>
              <%= favorite.teammate_recruitment.title %>
            </td>
            <td>
              <%= favorite.teammate_recruitment.group.category %>
            </td>
            <td>
              <%= favorite.teammate_recruitment.level %>
            </td>
            <td>
              <%= favorite.teammate_recruitment.created_at.strftime("%Y年%m月%d日") %>
            </td>
            <td>
              <%= link_to "詳細へ", teammate_recruitment_path(favorite.teammate_recruitment_id) ,class: "nav-link"%>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
    <%= paginate @teammate_favorites, class: "paginate" %>
  </div>
</div>

app/views/teammate_favorites/create.js.erb
$('#favorites_buttons_<%= @teammate_recruitment.id %>').html("<%= j(render partial: 'teammate_favorites/favorites_button', locals: {teammate_recruitment: @teammate_recruitment}) %>");

app/views/teammate_favorites/destroy.js.erb
$('#favorites_buttons_<%= @teammate_recruitment.id %>').html("<%= j(render partial: 'teammate_favorites/favorites_button', locals: {teammate_recruitment: @teammate_recruitment}) %>");

app/views/teammate_favorites/index.html.erb
<h2 class="mt-5">お気に入り一覧</h2>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a href="#favorite1" class="nav-link active" data-toggle="tab">メンバー募集</a>
  </li>
  <li class="nav-item">
    <a href="#favorite2" class="nav-link" data-toggle="tab">マッチメイク</a>
  </li>
</ul>

 <div class="tab-content">
  <div id="favorite1" class="tab-pane active">
    <%= render "teammate_favorite", teammate_favorites: @teammate_favorites %>
  </div>
  <div id="favorite2" class="tab-pane">
    <%= render "matchmake_favorites/matchmake_favorite", matchmake_favorites: @matchmake_favorites %>
  </div>
</div>