config/routes.rb
Rails.application.routes.draw do
  
  # devise_for :admins, controllers: {
  #   sessions:      'admins/sessions'
  # }
  devise_for :end_users, controllers: {
    sessions:      'end_users/sessions',
    passwords:     'end_users/passwords',
    registrations: 'end_users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'about' => 'homes#about', as: 'about'
  
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    get 'favorites' => 'teammate_favorites#index'
    # resources :teammate_favorites, only: [:index]
    resources :group_users, only: [:index]
  end
  resources :groups, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get 'post_index' => 'groups#post_index'
    get 'menber_index' => 'groups#menber_index'
    resources :matchmakes, only: [:new, :create, :edit, :update, :destroy] 
    resources :teammate_recruitments, only: [:new, :create, :edit, :update, :destroy] 
    resource :group_users, only: [:create, :destroy]
  end
  resources :teammate_recruitments, only: [:index, :show] do
    resources :teammate_comments, only: [:create, :destroy]
    resource :teammate_favorites, only: [:create, :destroy]
  end
  resources :matchmakes, only: [:index, :show] do
    resources :matchmake_comments, only: [:create, :destroy]
    resource :matchmake_favorites, only: [:create, :destroy]
  end
  

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :end_users, through: :group_users
  has_many :teammate_recruitments, dependent: :destroy
  has_many :matchmakes, dependent: :destroy
  
  belongs_to :end_user

  def join_by?(end_user)
		group_users.where(end_user_id: end_user.id).exists?
	end
  
  # rifileで画像を登録できるようにするための記述
  attachment :group_image
  enum city: {"千代田区":0, "中央区":1, "港区":2, "新宿区":3, "文京区":4, "台東区":5, "墨田区":6, "江東区":7, "品川区":8, "目黒区":9, "大田区":10, "世田谷区":11, "渋谷区":12, "中野区":13, "杉並区":14, "豊島区":15, "北区":16, "荒川区":17, "板橋区":18, "練馬区":19, "足立区":20, "葛飾区":21, "江戸川区":22}
  enum category: {"男性":0, "女性":1, "ミックス":2, "オーバー30":3, "オーバー40":4}
  enum level: {"超初級ーウルトラビギナー":0, "初級－スーパービギナー":1, "中級－ビギナー":2, "上級－エンジョイ":3}

  # チーム名による絞り込み
  scope :get_by_name, ->(name) {
  where("name like ?", "%#{name}%")
  }
  # 活動地域による絞り込み
  scope :get_by_city, ->(city) {
  where(city: city)
  }
  # カテゴリーによる絞り込み
  scope :get_by_category, ->(category) {
    where(category: category)
  }

  validates :name, presence: true, length: {maximum: 20 }
  validates :city, presence: true
  validates :category, presence: true
  validates :level, presence: true
  # 半角数字のみ
  validates :male_member, format: { with:/\A[0-9]+\z/}
  validates :female_member, format: { with:/\A[0-9]+\z/}
  validates :average_age, format: { with:/\A[0-9]+\z/}
  validates :group_introduction, presence: true,length: {maximum: 1000 }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_end_user!,except: [:index, :show, :menber_index]
  # ユーザー本人とAdminしか下記のアクションを行えないようにする
  before_action :ensure_correct_user,{only: [:edit,:update,:destroy]}
  def index
    # 新しい順に上から表示（降順）,８投稿毎にページをかえる
    @groups = Group.all.order(created_at: :desc).page(params[:page]).per(8)
    # モデルに定義した絞り込み検索の記述を呼び出す
    if params[:name].present?
    @groups = @groups.get_by_name params[:name]
    end
    if params[:city].present?
    @groups = @groups.get_by_city params[:city]
    end
    if params[:category].present?
    @groups = @groups.get_by_category params[:category]
    end
  end

  def new
    @group = Group.new
    @group.end_users << current_end_user
  end

  def create
    @group = Group.new(group_params)
    #end_user_id=グループ作成者と定義
    @group.end_user_id = current_end_user.id
    if @group.save
    # グループを作成時にGroupUserにIDが保存される処理
      @group_user = GroupUser.new
      # 保存先を指定
      @group_user.end_user_id = @group.end_user_id
      @group_user.group_id = @group.id
      @group_user.save
      redirect_to group_path(@group), notice: "チームを作成しました"
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to @group ,notice: "チーム編集が完了しました"
    else
      render :edit
    end
  end

  def show
  @group = Group.find(params[:id])
  @menbers = GroupUser.where(group_id: @group.id).count
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
    redirect_to root_path
  end

  def post_index 
    @group = Group.find(params[:group_id])
    @matchmakes = Matchmake.where(group_id: @group).order(created_at: :desc).page(params[:page]).per(8)
    @teammate_recruitments = TeammateRecruitment.where(group_id: @group).order(created_at: :desc).page(params[:page]).per(8)
  end

  def menber_index
    @group = Group.find(params[:group_id])
    @menbers = GroupUser.where(group_id: @group.id)
  end

  private
  def group_params
    params.require(:group).permit(:name, :city, :place, :category, :male_member, :female_member, :average_age, :level, :group_introduction, :group_image, end_user_ids: [])
  end

  def ensure_correct_user
    @group = Group.find_by(id: params[:id])
    if @group.end_user_id != current_end_user.id && current_end_user.admin == false
    redirect_to root_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for group do |f| %>
  <%= render 'layouts/error_messages', record: @group %>
  <div class="row">
    <div class="col-8 offset-2">
      <table class="table">
        <tr>
          <th>チーム名</th>
          <td>
            <%= f.text_field :name, placeholder:"チームFCON(20文字以内)",size: 45 %>
          </td>
        </tr>
        <tr>
        <th>地域</th>
          <td>
            <%= f.select :city, Group.cities.keys.to_a, {}  %>
          </td>
        </tr>
        <tr>
          <th>ホームグラウンド</th>
          <td>
            <%= f.text_field :place, placeholder:"FCONフットサル場(任意)",size: 45  %>
          </td>
        </tr>
        <tr>
        <th>カテゴリー</th>
          <td>
            <%= f.select :category, Group.categories.keys.to_a, {}  %>
          </td>
        </tr>
        <tr>
        <th>レベル</th>
          <td>
            <%= f.select :level, Group.levels.keys.to_a, {}  %>
          </td>
        </tr>
        <tr>
        <th>男女比</th>
          <td>
            男性<%= f.number_field :male_member, min: 0 ,max:99%>人<span>　</span>
            女性<%= f.number_field :female_member, min: 0 ,max:99%>人
          </td>
        </tr>
        <tr>
        <th>平均年齢</th>
          <td>
            <%= f.number_field :average_age, min: 0 ,max:99%>歳
          </td>
        </tr>
        <tr>
          <th>チーム画像</th>
          <td>
            <%= f.attachment_field :group_image, placeholder: "画像選択" %>
          </td>
        </tr>
        <tr>
          <th>チーム紹介</th>
          <td>
            <%= f.text_area :group_introduction, placeholder:"こんにちは！！" ,size: "45*45"%>
          </td>
        </tr>
      </table>
      <div class="actions text-center">
        <%= f.submit "　　登 録 す る　　" ,class:"btn btn-outline-primary btn-sm " %>
      </div>
    </div>
  </div>
<% end %>

app/views/groups/_matchmake_post.html.erb
<h2 class="mt-5">マッチメイク投稿一覧</h2>
<div class="row">
  <div class="col-8 offset-2">
    <table class="table">
      <thead>
        <tr>
          <th>投稿タイトル</th>
          <th>投稿日</th>
          <th></th>
          <th><th>
        </tr>
      </thead>
      <% matchmakes.each do |matchmake| %>
        <tbody>
          <tr>
            <td>
              <%= matchmake.title %>
            </td>
            <td ><%= matchmake.created_at.strftime("%Y年%m月%d日") %></td>
            <td >
              <%= link_to "詳細へ", matchmake_path(matchmake.id),class: "nav-link" %>
            </td>
            <%# 現在のログインユーザーがグループ作成者であれば以下を表示 %>
            <% if matchmake.group.end_user_id == current_end_user.id %>
              <td>
                <%= link_to "投稿を削除する", group_matchmake_path(matchmake.group,matchmake), method: :delete, "data-confirm" => "本当に消しますか？",class:"btn btn-outline-danger btn-sm " %>
              </td>
            <% end %>
          </tr>
        </tbody>
      <% end %>
    </table>
    <%= paginate matchmakes, class: "paginate" %>
  </div>
</div>

app/views/groups/_teammate_recruitment_post.html.erb
<h2 class="mt-5">メンバー募集投稿一覧</h2>
<div class="row">
  <div class="col-8 offset-2">
    <table class="table">
      <thead>
        <tr>
          <th>投稿タイトル</th>
          <th>投稿日</th>
          <th></th>
          <th><th>
        </tr>
      </thead>
      <% teammate_recruitments.each do |teammate_recruitment| %>
        <tbody>
          <tr>
            <td>
              <%= teammate_recruitment.title %>
            </td>
            <td ><%= teammate_recruitment.created_at.strftime("%Y年%m月%d日") %></td>
            <td >
              <%= link_to "詳細へ", teammate_recruitment_path(teammate_recruitment.id),class: "nav-link" %>
            </td>
            <%# 現在のログインユーザーがグループ作成者であれば以下を表示 %>
            <% if teammate_recruitment.group.end_user_id == current_end_user.id %>
              <td>
                <%= link_to "投稿を削除する", group_teammate_recruitment_path(teammate_recruitment.group,teammate_recruitment), method: :delete, "data-confirm" => "本当に消しますか？",class:"btn btn-outline-danger btn-sm " %>
              </td>
            <% end %>
          </tr>
        </tbody>
      <% end %>
    </table>
    <%= paginate teammate_recruitments, class: "paginate" %>
  </div>
</div>

app/views/groups/edit.html.erb
<h2 class="mt-5 mb-4">チーム編集</h2>
<%= render "form" ,group: @group%>

app/views/groups/index.html.erb
<h2 class="mt-5">チーム一覧</h2>
<%# 絞り込み機能%>
<div class="row">
  <div class = "col-6">
    <%= form_tag(groups_path, method: "get") do %>
      <table class="table table-borderless"> 
          <tr>
            <td>
              <strong>チーム名</strong><br>
              <span>
                <%= text_field_tag :name, params[:name],size: 35 %>
              </span>
            </td>
            <td><strong>活動地域</strong><br>
              <span>
                <%= select_tag :city, options_for_select(Group.cities), include_blank: true %>
              </span>
            </td>
            <td><strong>カテゴリー</strong><br>
              <span>
                <%= select_tag :category, options_for_select(Group.categories), include_blank: true %>
              </span>
            </td>
            <td><br><span><%= submit_tag "検索" %></span></td>
          </tr>
      </table>
    <% end %>
  </div>
</div>
<%# 絞り込み機能ここまで%>
<div class="row">
  <div class="col-10 offset-1">
    表示件数：<%= @groups.count%>件
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>チーム名</th>
          <th>活動地域</th>
          <th>カテゴリー</th>
          <th>レベル</th>
          <th></th>
        </tr>
      </thead>
      <% if  @groups.present? %>
        <% @groups.each do |group|%>
          <tbody>
            <tr>
              <td>
                <%= attachment_image_tag group, :group_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image2.jpg", size: "50x50"%>
              </td>
              <td><%= group.name %></td>
              <td><%= group.city %></td>
              <td><%= group.category %></td>
              <td><%= group.level %></td>
              <td>
              <%= link_to "チーム詳細へ", group_path(group.id),class: "nav-link" %>
              </td>
            </tr>
          </tbody>
        <% end %>
      <% else %>
        <h4>検索結果はありません</h4>
    <% end %>
    </table>
    <%= paginate @groups, class: "paginate" %>
  </div>
</div>

app/views/groups/matchmake_index.html.erb
<h2>マッチメイク投稿一覧</h2>
<div class="row">
  <div class="col-8 offset-2">
    <table class="table">
      <thead>
        <tr>
          <th>投稿タイトル</th>
          <th>投稿日</th>
          <th></th>
          <th><th>
        </tr>
      </thead>
      <% @matchmakes.each do |matchmake| %>
        <tbody>
          <tr>
            <td>
              <%= matchmake.title %>
            </td>
            <td ><%= matchmake.created_at.strftime("%Y年%m月%d日") %></td>
            <td >
              <%= link_to "詳細へ", matchmake_path(matchmake.id) %>
            </td>
            <td>
              <%= link_to "投稿を削除する", group_matchmake_path(matchmake.group,matchmake), method: :delete, "data-confirm" => "本当に消しますか？",class:"btn btn-danger btn-sm " %>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/groups/menber_index.html.erb
<h2 class="mt-5"><%= @group.name%>のメンバー</h2>
<div class="row">
  <div class="col-10 offset-1">
    <table class="table">
      <thead>
        <tr>
          <th><th>
          <th>ニックネーム</th>
          <th>年齢</th>
          <th>フットサル経験</th>
          <th>サッカー経験</th>
          <th></th>
        </tr>
      </thead>
      <% @menbers.each do |menber| %>
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag menber.end_user, :user_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg"%>
            </td>
            <td>
              <%= menber.end_user.nick_name %>
            </td>
            <td>
              <%= menber.end_user.age%>
            </td>
            <td><%= menber.end_user.fotsal_experience %>年</td>
            <td><%= menber.end_user.soccer_experience %>年</td>
            <td>
              <%= link_to "詳細へ", user_path(menber.end_user_id),class: "nav-link" %>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
    
  </div>
</div>

app/views/groups/new.html.erb
<h2 class="mt-5 mb-4">チーム作成</h2>
<%= render 'form', group: @group %>

app/views/groups/post_index.html.erb
<h2 class="mt-5">投稿一覧</h2>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a href="#join" class="nav-link active" data-toggle="tab">メンバー募集</a>
  </li>
  <li class="nav-item">
    <a href="#create" class="nav-link" data-toggle="tab">マッチメイク</a>
  </li>
</ul>

 <div class="tab-content">
  <div id="join" class="tab-pane active">
    <%= render "teammate_recruitment_post", teammate_recruitments: @teammate_recruitments %>
  </div>
  <div id="create" class="tab-pane">
    <%= render "matchmake_post", matchmakes: @matchmakes %>
  </div>
</div>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>
<h2 class="mt-5">チーム詳細</h2>
<div class="row">
  <div class="col-4 offset-1">
    <table class="table table-borderless">
      <tr>
        <td class="image">
        <%= attachment_image_tag @group, :group_image, :fill, 300, 300, format: 'jpeg', fallback: "no_image2.jpg"%>
        </td>
      </tr>
      <tr>
        <td>
          <strong>チーム作成者：</strong>
          <%= link_to user_path(@group.end_user),class: "link" do %>
            <%= @group.end_user.nick_name %>
          <% end %><br>
          <strong>所属メンバー：</strong>
          <%= link_to group_menber_index_path(@group),class: "link" do %>
            <%= @menbers%>人
          <% end %>
        </td>
      </tr>
      <tr>
        <td>
          
        </td>
      </tr>
      <%# ログインしてないユーザーの場合表示しない %>
      <% if end_user_signed_in?%>
      <%# group作成者のend_user_idとログインユーザーidが一緒なら表示 %>
        <% if @group.end_user_id == current_end_user.id %>
          <tr>
            <td>
              <%= link_to "編集する",edit_group_path(@group) ,class: "btn btn-outline-secondary btn-sm btn-block" %>
            </td>
          </tr>
          <tr>
            <td>
              <%= link_to "チームを削除する", group_path, method: :delete, "data-confirm" => "本当に消しますか？",class:"btn btn-outline-danger btn-sm btn-block" %>
            </td>
          </tr>
          <tr>
            <td>
              <%= link_to "投稿一覧", group_post_index_path(@group),class: "btn btn-outline-primary btn-sm btn-block"  %>
            </td>
          </tr>
          <tr>
            <td>
              <%= link_to "新メンバーを募集する", new_group_teammate_recruitment_path(@group),class: "btn btn-outline-success btn-sm btn-block" %>
            </td>
          </tr>
          <tr>
            <td>
              <%= link_to "マッチメイクを募集する", new_group_matchmake_path(@group) ,class: "btn btn-outline-success btn-sm btn-block"%>
            </td>
          </tr>
          <%# ログインユーザーがAdminなら以下の情報が表示 %>
          <% elsif current_end_user.admin == true %>
            <tr>
              <td>
                <%= link_to "チームを削除する", group_path, method: :delete, "data-confirm" => "本当に消しますか？",class:"btn btn-outline-danger btn-sm btn-block" %>
              </td>
            </tr>
            <tr>
            <td>
              <%= link_to "投稿一覧", group_post_index_path(@group),class: "btn btn-outline-primary btn-sm btn-block"  %>
            </td>
          </tr>
          <% else %>
          <tr>
            <td>
              <%= link_to "投稿一覧", group_post_index_path(@group),class: "btn btn-outline-primary btn-sm btn-block"  %>
            </td>
          </tr>
          <tr>
            <td>
            <%# チーム参加、脱退機能 %>
              <div id="group_users_buttons_<%= @group.id %>">
                <%= render partial: 'group_users/join_button', locals: {group: @group} %>
              </div>
              <%# チーム参加、脱退機能ここまで %>
            </td>
          </tr>
        <% end %>
      <% end %>
      <%# ここまで %>
    </table>
  </div>
  <div class="col-6">
    <table class="group_table table table-bordered">
      <tr>
        <th>チーム名</th>
        <td><%= @group.name %></td>
      </tr>
      <tr>
        <th>活動地域</th>
        <td><%= @group.city %></td>
      </tr>
      <tr>
        <th>ホームグランド</th>
        <td><%= @group.place %></td>
      </tr>
      <tr>
        <th>カテゴリー</th>
        <td><%= @group.category %></td>
      </tr>
      <tr>
        <th>レベル</th>
        <td><%= @group.level %></td>
      </tr>
      <tr>
        <th>平均年齢</th>
        <td><%= @group.average_age %>歳</td>
      </tr>
        <th>男女比</th>
        <td>
          男性<%= @group.male_member %>人 :
          女性<%= @group.female_member %>人
        </td>
      </tr>
    </table>
    <table class="table table-bordered">
      <tr><strong>チーム紹介</strong></tr>
      <%# 入力された段落通りに表示 %>
      <td><%= simple_format(@group.group_introduction) %></td>
    </table>
  </div>
</div>

app/views/groups/teammate_recruitment_index.html.erb
<h2>メンバー募集投稿一覧</h2>
<div class="row">
  <div class="col-8 offset-2">
    <table class="table">
      <thead>
        <tr>
          <th>投稿タイトル</th>
          <th>投稿日</th>
          <th></th>
          <th><th>
        </tr>
      </thead>
      <% @teammate_recruitments.each do |teammate_recruitment| %>
        <tbody>
          <tr>
            <td>
              <%= teammate_recruitment.title %>
            </td>
            <td ><%= teammate_recruitment.created_at.strftime("%Y年%m月%d日") %></td>
            <td >
              <%= link_to "詳細へ", teammate_recruitment_path(teammate_recruitment.id) %>
            </td>
            <td>
              <%= link_to "投稿を削除する", group_teammate_recruitment_path(teammate_recruitment.group,teammate_recruitment), method: :delete, "data-confirm" => "本当に消しますか？",class:"btn btn-danger btn-sm " %>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>