config/routes.rb
Rails.application.routes.draw do
  
  # devise_for :admins, controllers: {
  #   sessions:      'admins/sessions'
  # }
  devise_for :end_users, controllers: {
    sessions:      'end_users/sessions',
    passwords:     'end_users/passwords',
    registrations: 'end_users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get 'about' => 'homes#about', as: 'about'
  
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    get 'favorites' => 'teammate_favorites#index'
    # resources :teammate_favorites, only: [:index]
    resources :group_users, only: [:index]
  end
  resources :groups, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get 'post_index' => 'groups#post_index'
    get 'menber_index' => 'groups#menber_index'
    resources :matchmakes, only: [:new, :create, :edit, :update, :destroy] 
    resources :teammate_recruitments, only: [:new, :create, :edit, :update, :destroy] 
    resource :group_users, only: [:create, :destroy]
  end
  resources :teammate_recruitments, only: [:index, :show] do
    resources :teammate_comments, only: [:create, :destroy]
    resource :teammate_favorites, only: [:create, :destroy]
  end
  resources :matchmakes, only: [:index, :show] do
    resources :matchmake_comments, only: [:create, :destroy]
    resource :matchmake_favorites, only: [:create, :destroy]
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_end_user!,except: [:index, :show]
  # ユーザー本人とAdminしか下記のアクションを行えないようにする
  before_action :ensure_correct_user,{only: [:edit,:update,:destroy]}
  def index
    # 新しい順に上から表示（降順）８人毎にページをかえる
    @users = EndUser.all.order(created_at: :desc).page(params[:page]).per(8)
    # モデルに定義した絞り込み検索の記述を呼び出す
    if params[:nick_name].present?
    @users = @users.get_by_nick_name params[:nick_name]
    end
    if params[:age].present?
    @users = @users.get_by_age params[:age]
    end
  end

  def show
    @user = EndUser.find(params[:id])
  end

  def edit
    @user = EndUser.find(params[:id])
  end

  def update
    @user = EndUser.find(params[:id])
    if @user.update(end_user_params)
    redirect_to user_path(@user.id), notice: "編集が完了しました"
    else
      render :edit
    end
  end

  def destroy
    user = EndUser.find(params[:id])
    user.destroy
    # グループ作成者が退会した場合は、グループに紐づくデータ（グループ参加者や投稿を全て削除
    group = Group.where(end_user_id: user.id)
    group.destroy_all
    redirect_to root_path
  end

  private
  def end_user_params
    params.require(:end_user).permit(:nick_name, :phone_number, :gender, :age, :fotsal_experience, :soccer_experience, :introduction, :user_image, :email, :deleted_at)
  end

  def ensure_correct_user
    @user = EndUser.find_by(id: params[:id])
    if @user.id != current_end_user.id && current_end_user.admin == false
        redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2 class="mt-5 mb-4">登録情報編集</h2>

<%= form_for @user, url: user_path do |f| %>
<%= render 'layouts/error_messages', record: @user %>
  <div class="row">
    <div class="col-3 offset-1">
      <%= attachment_image_tag @user, :user_image, :fill, 250, 250, format: 'jpeg', fallback: "no_image.jpg", size: "250x250"%>
      <%= f.attachment_field :user_image, placeholder: "画像選択" %>
    </div>
    <div class="col-7">
      <table class="table">
        <tr>
          <th>ニックネーム</th>
          <td><%= f.text_field :nick_name, placeholder:"FCON太郎(10文字以内)",size: 30%></td>
        </tr>
        <tr>
          <th>電話番号</th>
            <td>
              <%= f.telephone_field :phone_number, placeholder: "090-1234-5678(ハイフン)", size: 30%>
            </td>
        </tr>
        <tr>
          <th>メールアドレス</th>
            <td>
              <%= f.email_field :email, placeholder: "fcon@fmail.com", size: 30%>
            </td>
        </tr>
        <tr>
          <th>性別</th>
            <td>
              <%= f.select :gender, EndUser.genders.keys.to_a, {}  %>
            </td>
        </tr>
        <tr>
          <th>年齢</th>
            <td>
              <%= f.select :age, EndUser.ages.keys.to_a, {} %>
            </td>
        </tr>
        <tr>
          <th>フットサル経験</th>
            <td>
              <%= f.number_field :fotsal_experience, min: 0 ,max:99%>年
            </td>
        </tr>
        <tr>
          <th>サッカー経験</th>
            <td>
              <%= f.number_field :soccer_experience,min: 0 ,max:99 %>年
            </td>
        </tr>
        <tr>
          <th>自己紹介etc</th>
          <td>
            <%= f.text_area :introduction, placeholder:"こんにちは！！(任意）",size: "30*30" %>
          </td>
        </tr>
      </table>
      <div class="actions text-center">
        <%= f.submit "　　登 録 す る　　" ,class:"btn btn-outline-primary btn-sm " %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<h2 class="mt-5">会員一覧</h2>
<%#　絞り込み機能%>
<div class="row">
  <div class = "col-4">
    <%= form_tag(users_path, method: "get") do %>
      <table class="table table-borderless"> 
          <tr>
            <td>
              <strong>ニックネーム</strong><br>
              <span>
                <%= text_field_tag :nick_name, params[:nick_name],size: 35 %>
              </span>
            </td>
            <td><strong>年齢</strong><br>
              <span>
                <%= select_tag :age, options_for_select(EndUser.ages), include_blank: true %>
              </span>
            </td>
            <td><br><span><%= submit_tag "検索" %></span></td>
          </tr>
      </table>
    <% end %>
  </div>
</div>
<%# 絞り込み機能ここまで%>
<div class="row">
  <div class="col-10 offset-1">
      表示件数：<%= @users.count%>件
    <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>ニックネーム</th>
            <th>年齢</th>
            <th>フットサル経験</th>
            <th>サッカー経験</th>
            <th></th>
          </tr>
        </thead>
        <% if  @users.present? %>
          <% @users.each do |user| %>
            <tbody>
              <tr>
                <td>
                  <%= attachment_image_tag user, :user_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" , size: "50x50"%>
                </td>
                <td><%= user.nick_name%></td>
                <td><%= user.age%></td>
                <td><%= user.fotsal_experience %>年</td>
                <td><%= user.soccer_experience %>年</td>
                <td>
                  <%= link_to "会員詳細へ", user_path(user.id),class: "nav-link" %>
                </td>
              </tr>
            </tbody>
          <% end %>
        <% else %>
          <h4>検索結果はありません</h4>
      <% end %>
    </table>
    <%= paginate @users, class: "paginate" %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<% if @user == current_end_user %>
  <h2 class="mt-5">マイページ</h2>
<% else  %>
  <h2 class="mt-5"><%= @user.nick_name%>さんのページ</h2>
<% end %>
<div class="row">
  <div class="col-4 offset-1">
    <table class="table table-borderless">
      <tr>
        <td class="image">
        <%= attachment_image_tag @user, :user_image, :fill, 250, 250, format: 'jpeg', fallback: "no_image.jpg", size: "250x250" %>
        </td>
      </tr>
      <%# ログインしてないユーザーの場合表示しない %>
      <% if end_user_signed_in?%>
      <%# ログインユーザーと@userが一緒なら以下の情報が表示 %>
        <% if @user == current_end_user %>
          <tr>
            <td>
              <%= link_to "編集する",edit_user_path(@user) ,class: "btn btn-outline-secondary btn-sm btn-block" %>
            </td>
          </tr>
          <tr>
            <td>
            <%= link_to "退会する", user_path, method: :delete, "data-confirm" => "本当に退会しますか？",class:"btn btn-outline-danger btn-sm btn-block" %>
            <td>
          </tr>
          <tr>
            <td><%= link_to "チームを作成する", new_group_path ,class: "btn btn-outline-success btn-sm btn-block"%></td><br>
          </tr>
        <%# ログインユーザーがAdminなら以下の情報が表示 %>
        <% elsif current_end_user.admin == true %>
          <tr>
            <td>
              <%= link_to "削除する", user_path, method: :delete, "data-confirm" => "本当に消しますか？",class:"btn btn-outline-danger btn-sm btn-block" %>
            <td>
          </tr>
        <% else current_end_user.admin == false%>
        <% end %>
      <% end %>
      <%# ここまで %>
    </table>
  </div>
  <div class="col-6">
    <table class="user_table table table-bordered">
      <tr>
        <th>ニックネーム</th>
        <td><%= @user.nick_name %></td>
      </tr>
      <%# ログインしてないユーザーの場合表示しない %>
      <% if end_user_signed_in?%>
      <%# ログインユーザーと@userが一緒なら以下の情報が表示 %>
        <% if @user == current_end_user || current_end_user.admin? %>
      <tr>
        <th>メールアドレス</th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= @user.phone_number %></td>
      </tr>
      <% end %>
      <% end %>
      <%# ここまで %>
      <tr>
        <th>性別</th>
        <td><%= @user.gender %></td>
      </tr>
      <tr>
        <th>年齢</th>
        <td><%= @user.age %></td>
      </tr>
      <tr>
        <th>フットサル経験</th>
        <td><%= @user.fotsal_experience %>年</td>
      </tr>
      <tr>
        <th>サッカー経験</th>
        <td><%= @user.soccer_experience %>年</td>
      </tr>
    </table>
    <table class="table table-bordered">
      <tr><strong>自己紹介</strong></tr>
      <%# 入力された段落通りに表示 %>
      <td><%= simple_format(@user.introduction) %></td>
    </table>
      
  </div>
</div>